refactor: dark mode tweaks for upload components
ArkEcosystem/laravel-foundation pull request #110
Opened 2021-11-15 15:05 UTC by Highjhacker

## Summary

https://app.clickup.com/t/1ravtrv

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

2021-11-17 14:24 UTC, stefro requested changes
Dark changes are good. But I think the spacing between the box and the dotted line is to big compared to the Figma design. I think it should be `p-1.5`. Can you check this?

2021-11-17 14:24 UTC, stefro commented on resources/views/inputs/upload-image-single.blade.php
> +        'p-2 border-2 border-dashed border-theme-primary-100 dark:border-theme-secondary-800' => ! $image,
It's not part of your PR, but when I look at the design in Figma, I think `p-2` should be `p-1.5`

2021-11-17 14:24 UTC, stefro commented on resources/views/inputs/upload-image-collection.blade.php
> +    <div class="rounded-xl p-2 border-2 border-dashed border-theme-primary-100 dark:border-theme-secondary-800 relative {{ $dimensions }} group">
It's not part of your PR, but when I look at the design in Figma, I think p-2 should be p-1.5

2021-11-18 09:59 UTC, stefro approved these changes

2021-11-18 11:10 UTC, ItsANameToo approved these changes

2021-11-18 11:13 UTC, merged