fix: rich select keyboard navigation not working
ArkEcosystem/laravel-foundation pull request #23
Opened 2021-10-06 20:14 UTC by alfonsobries

## Summary

https://app.clickup.com/t/1jv4f5v

Dependant of: https://github.com/ArkEcosystem/nodem/pull/277

refactor the way it gets the options count (used in the keyboard navigation) since the current implement loses the value after livewire re-renders the content.

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] I provided a screenshot of my changes to the component _(if applicable)_
-   [x] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-10-07 21:40 UTC, alexbarnsley requested changes
Using the keyboard to go down still seems to go only as far as the second option :thinking: if i then go back up, then try to go up again (e.g. selected index -1) i get a console error:

![image](https://user-images.githubusercontent.com/8069294/136465599-d614fc6b-ba8f-4b10-802c-8e181047c851.png)

~Added video to clickup card~

Nevermind - I missed the nodem PR!

2021-10-07 21:40 UTC, alexbarnsley commented on resources/assets/js/rich-select.js
> +        console.log(this.options);
debug

2021-10-11 09:23 UTC, alexbarnsley requested changes
As per the comment, when going "up" to the last item in the list, then "down" to the first, it actually goes to the second (index 1). I've posted a video in the clickup card

2021-10-11 09:23 UTC, alexbarnsley commented on resources/assets/js/rich-select.js
> +            this.selected + 1 > optionsCount - 1 ? 1 : this.selected + 1;
this should reset to 0, not 1

```suggestion
            this.selected + 1 > optionsCount - 1 ? 0 : this.selected + 1;
```

2021-10-13 12:50 UTC, ItsANameToo approved these changes

2021-10-13 12:50 UTC, merged