refactor: add twitter dark mode embeds
ArkEcosystem/laravel-foundation pull request #424
Opened 2022-07-25 16:28 UTC by alfonsobries

## Summary

https://app.clickup.com/t/2pz3235

This will allow the user to switch twitter embeds between dark and light

![image](https://user-images.githubusercontent.com/17262776/180828219-983a21be-839f-4e5f-80f1-19fda2f5e8fa.png)
![image](https://user-images.githubusercontent.com/17262776/180828258-2139b39d-32ff-4ff1-8fc4-bb176144331c.png)

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-07-26 08:57 UTC, ItsANameToo requested changes

2022-07-26 08:57 UTC, ItsANameToo commented on src/CommonMark/Extensions/Image/TwitterRenderer.php
> +        $darkModeEnabled = false;
🤔

2022-07-26 17:04 UTC, alfonsobries commented on src/CommonMark/Extensions/Image/TwitterRenderer.php
> +        $darkModeEnabled = false;
:wtf:

2022-07-26 17:07 UTC, alfonsobries commented on src/CommonMark/Extensions/Image/TwitterRenderer.php
> +        $darkModeEnabled = false;
@ItsANameToo fixed :hide:

2022-07-27 08:50 UTC, ItsANameToo approved these changes

2022-07-27 09:56 UTC, merged