chore: update to Tailwind v3
ArkEcosystem/laravel-foundation pull request #431
Opened 2022-07-27 09:15 UTC by crnkovic

## Summary

https://app.clickup.com/t/2nh847e

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-08-05 10:14 UTC, ItsANameToo requested changes
Needs to be checked with the `MarkdownPlugin` in foundation, as it doesn't work with that currently on projects that use that plugin in their webpack config.

2022-08-09 09:32 UTC, crnkovic commented
@ItsANameToo This no longer appears to be an issue for me on Node v16

![Screenshot 2022-08-09 at 11 32 02](https://user-images.githubusercontent.com/6536260/183615652-90dea030-39c5-4e92-9197-94ec8c6d750a.png)

2022-08-09 09:34 UTC, ItsANameToo commented
I'll have another look @crnkovic , thanks

2022-08-10 11:25 UTC, ItsANameToo approved these changes

2022-08-10 11:26 UTC, merged