refactor: footer component
ArkEcosystem/laravel-foundation pull request #446
Opened 2022-08-03 10:54 UTC by crnkovic

## Summary

https://app.clickup.com/t/2b006tr

TODO

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-08-04 12:47 UTC, ItsANameToo requested changes
- does this footer change cater for specifics like arkscan has with the marketdata addition:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/35610748/182850425-b5b03370-e6e9-4d7b-aa9e-765b0a8fedc2.png">

- does the default `x-ark-footer` still work? as the `layout.blade.php` template makes use of that in foundation 🤔 
- will be a breaking change with the removal of the old footer component, so make sure that it works on all projects (added them to the clickup card as subtasks)

2022-08-04 12:47 UTC, ItsANameToo commented on resources/views/footer.blade.php
> +    'arkProduct' => false,
```suggestion
    'isArkProduct' => false,
```

to make clear from the name it's a boolean

2022-08-04 12:47 UTC, ItsANameToo commented on resources/views/footer.blade.php
> +    'reservedRights' => true, // Show "All rights reserved"...
```suggestion
    'hasReservedRights' => true, // Show "All rights reserved"...
```

2022-08-04 12:47 UTC, ItsANameToo commented on resources/views/footer.blade.php
> +    'url' => null,
```suggestion
    'copyrightName' => null,
    'copyrightUrl' => null,
```

maybe? since they are only used there from what I saw

2022-08-04 12:47 UTC, ItsANameToo commented on resources/views/footer.blade.php
> +                    @lang ('ui::pages.footer.made_with_love') <a href="{{ $creator['url'] ?? url('/') }}" class="{{ $linkClass }}" target="_blank" rel="noopener">{{ is_string($creator) ? $creator : $
this has `target="_blank"` while we open urls in the same window when they point to the existing domain (e.g. ark.io links to ark.io as "made with love by" thing and does not open in a new tab when clicked, similar for ardenthq). 

basically it should depend on the URL whether it uses `_blank` or not

2022-08-04 14:15 UTC, crnkovic commented
@ItsANameToo good catch for ARKScan, added the ability to pass slot as custom content that's appended to the footer. Also added the ability to indicate whether to open links in new window or not. Will leave this as draft until I recreate footers from all projects.

Updated PR description with new stuff and new examples.

2022-08-09 09:27 UTC, ItsANameToo approved these changes

2022-08-09 09:28 UTC, merged